"""
DISTRITAL FRANCISCO JOSÉ DE CALDAS UNIVERSITY
COURSE: COMPUTER SCIENCES I (2026-I)

PROJECT: TREASURE HUNT
COMPONENT: INTERACTIVE PYGAME USER INTERFACE
"""

import json
import os

# Relative paths directed to the root data directory based on the official project layout
INPUT_PATH = "../data/input.json"
STATE_PATH = "../data/state.json"

def save_user_action(action_type, details=None):
    """
    Serializes and writes real-time player interactions, manual movements,
    or algorithm execution commands into input.json for the C++ engine to read.
    
    Parameters:
    - action_type (str): The primary operation identifier (e.g., 'MOVE', 'RUN_GREEDY').
    - details (dict): Metadata payload containing direction arguments or planned path arrays.
    """
    payload = {
        "action": action_type,
        "details": details if details else {}
    }
    
    # Structural verification: Ensure the data directory exists before any writing execution
    os.makedirs(os.path.dirname(INPUT_PATH), exist_ok=True)
    
    with open(INPUT_PATH, 'w') as input_file:
        json.dump(payload, input_file, indent=4)


def read_game_state():
    """
    Reads and deserializes the execution frame generated by the C++ engine core.
    Provides data to Pygame to update positions, items, and scoreboard state.
    
    Returns:
    - dict: Game state matrix containing player metrics, score, and active treasures.
    """
    # Fallback simulation block (Mock Data): Used to decouple UI testing from C++ binary execution
    if not os.path.exists(STATE_PATH):
        return {
            "player_pos": [0, 0],
            "score": 0,
            "movement_history": ["START"],
            "treasures": [
                {"x": 2, "y": 3, "value": 100, "name": "Bronze Chest"},
                {"x": 5, "y": 6, "value": 500, "name": "Golden Chalice"},
                {"x": 1, "y": 4, "value": 250, "name": "Silver Crown"},
                {"x": 6, "y": 2, "value": 300, "name": "Emerald Ring"}
            ]
        }
    
    with open(STATE_PATH, 'r') as state_file:
        return json.load(state_file)